### ISSUE TITLE
[UVT-13] loading of the last selected project does not work, if available

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/UniversalValveToolbox#12]
loading of the last selected project does not work, if any.

You need to fix it, maybe in json the project is saved. And also after loading, you need to add the creation \ rewrite of the variable in the user's environment.

**Comment by Aleks-Z** [comment]
almost done, but something went wrong. 

![obezyana-mem](https://user-images.githubusercontent.com/1307229/77164826-1cf15880-6ac2-11ea-8719-af9fa8aecdb8.jpg)

**Comment by stamepicmorg** [comment]
when choosing an engine, it will be necessary to record in user variables:
always `VProject` - full path to the project folder (the one in -game)

if sfm engine is selected, then additionally
`VContent` "path to the source folder SourceFilmmaker \ content"
`VGame` "path to the source folder of SourceFilmmaker \ game"
`VTools` "path to the source folder SourceFilmmaker \ game \ sdktools"

**Comment by stamepicmorg** [comment]
https://github.com/EpicMorg/UniversalValveToolbox/pull/11/commits/ca9bda7a570a3e4671a0a61bc387e8498a967479
https://github.com/EpicMorg/UniversalValveToolbox/pull/11/commits/e1cf1fa38790266d4d9d9284da8753f9eb509bea
https://github.com/EpicMorg/UniversalValveToolbox/pull/11/commits/9b45461af3b2f66298d3777c5bbc966a14e578ef
