### ISSUE TITLE
[UVT-6] if the projecst folder is empty, the project editor does not open

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/UniversalValveToolbox#4]
https://github.com/EpicMorg/UniversalValveToolbox/issues/3

![image](https://user-images.githubusercontent.com/1307229/75967646-2c2ab080-5edd-11ea-8ab4-cc664e9d52d2.png)

**Comment by stamepicmorg** [comment]
Move it to the sprint in which we will migrate to the `dotNet Core - wpf`.

**Comment by Aleks-Z** [comment]
fixed https://github.com/EpicMorg/UniversalValveToolbox/issues/4
