### ISSUE TITLE
[UVT-7] if I don’t have projects (empty projects folder) I can open programs from tools and catch an error

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/UniversalValveToolbox#5]
if I don’t have any projects (empty projects folder) I can open programs from tools and catch an error.

in the case of an empty project folder when you click on programs from tools - it is better to swear and ask to create a project.

There was a problem when I forcibly added the `-game` option to the entire tools section. in this commit: https://github.com/EpicMorg/UniversalValveToolbox/commit/b3ec2ff8351d3851d3aa0ed89b51efc42a412be5

https://github.com/EpicMorg/UniversalValveToolbox/issues/3
https://github.com/EpicMorg/UniversalValveToolbox/issues/4
https://github.com/EpicMorg/UniversalValveToolbox/issues/6

![image](https://user-images.githubusercontent.com/1307229/75967771-5ed4a900-5edd-11ea-9d16-47a73d231f29.png) 
![image](https://user-images.githubusercontent.com/1307229/75967777-61370300-5edd-11ea-9be0-d8b4ecf69fc6.png)

**Comment by Aleks-Z** [comment]
easy fix lol https://github.com/EpicMorg/UniversalValveToolbox/issues/5
