### ISSUE TITLE
[UVT-10] if the addons folder is empty, the project editor does not open

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/UniversalValveToolbox#8]
https://github.com/EpicMorg/UniversalValveToolbox/issues/7

![image](https://user-images.githubusercontent.com/1307229/75968346-46b15980-5ede-11ea-9559-77f477a00509.png)

**Comment by Aleks-Z** [comment]
fixed https://github.com/EpicMorg/UniversalValveToolbox/commit/3a33fde10abdf68ba62ab96b4550f570b8307eb8
