### ISSUE TITLE
[UVT-11] It is necessary to offer to install unidentified engines. Or hide at all.

### ISSUE THREAD

**Issue by stamepicmorg** [EpicMorg/UniversalValveToolbox#9]
It is necessary to offer to install unidentified engines. Or hide at all.

![image](https://user-images.githubusercontent.com/1307229/75968785-00102f00-5edf-11ea-86c9-27496d15c738.png)

 
![image](https://user-images.githubusercontent.com/1307229/75969054-672de380-5edf-11ea-805a-2fb26e9fe741.png)

**Comment by stamepicmorg** [comment]
https://github.com/EpicMorg/UniversalValveToolbox/commit/0f753551424f270f7d29a67fc98008521c04c411

![bandicam-2020-03-05-12-57-15-202](https://user-images.githubusercontent.com/1307229/75970428-5d0ce480-5ee1-11ea-9480-e145642cffde.gif)

**Comment by Aleks-Z** [comment]
### todo

- [x] add setting to hide uninstalled user engines (on by default)
- [x] add a setting to hide engines that are not purchased \ are not tied to an account (on by default) [now these engines simply hide in the code]

**Comment by stamepicmorg** [comment]
decided to hide the invalid engines.

settings will be in 2.0 version
